INSERT INTO "FABIO"."VOLCANOCALDERA" (VOLCANOIDENTIFIER, LOCALNAME) VALUES ('CMP', 'Campi Flegrei');
INSERT INTO "FABIO"."VOLCANOCALDERA" (VOLCANOIDENTIFIER, LOCALNAME) VALUES ('TBA', 'Toba');
INSERT INTO "FABIO"."VOLCANOCALDERA" (VOLCANOIDENTIFIER, LOCALNAME) VALUES ('TPO', 'Taupo');

INSERT INTO "FABIO"."VOLCANOACTIVE" (VOLCANOIDENTIFIER, LOCALNAME) VALUES ('TNA', 'Etna');
INSERT INTO "FABIO"."VOLCANOACTIVE" (VOLCANOIDENTIFIER, LOCALNAME) VALUES ('RPH', 'Ruapehu');
INSERT INTO "FABIO"."VOLCANOACTIVE" (VOLCANOIDENTIFIER, LOCALNAME) VALUES ('TRW', 'Tarawera');

INSERT INTO "FABIO"."VOLCANOINACTIVE" (VOLCANOIDENTIFIER, LOCALNAME) VALUES ('MKS', 'Emi Koussi');
INSERT INTO "FABIO"."VOLCANOINACTIVE" (VOLCANOIDENTIFIER, LOCALNAME) VALUES ('VLT', 'Vulture');
INSERT INTO "FABIO"."VOLCANOINACTIVE" (VOLCANOIDENTIFIER, LOCALNAME) VALUES ('MTA', 'Amiata');

UPDATE "FABIO"."VOLCANOCALDERA" SET ISDECADE = '0' WHERE VOLCANOIDENTIFIER = 'CMP';
UPDATE "FABIO"."VOLCANOCALDERA" SET ISDECADE = '0' WHERE VOLCANOIDENTIFIER = 'TBA';
UPDATE "FABIO"."VOLCANOCALDERA" SET ISDECADE = '0' WHERE VOLCANOIDENTIFIER = 'TPO';

UPDATE "FABIO"."VOLCANOACTIVE" SET ISDECADE = '0' WHERE VOLCANOIDENTIFIER = 'TNA';
UPDATE "FABIO"."VOLCANOACTIVE" SET ISDECADE = '0' WHERE VOLCANOIDENTIFIER = 'RPH';
UPDATE "FABIO"."VOLCANOACTIVE" SET ISDECADE = '0' WHERE VOLCANOIDENTIFIER = 'TRW';

UPDATE "FABIO"."VOLCANOINACTIVE" SET SMITHSONIANIDENTIFIER = '12345' WHERE VOLCANOIDENTIFIER = 'MKS';
UPDATE "FABIO"."VOLCANOINACTIVE" SET SMITHSONIANIDENTIFIER = '12345' WHERE VOLCANOIDENTIFIER = 'VLT';
UPDATE "FABIO"."VOLCANOINACTIVE" SET SMITHSONIANIDENTIFIER = '12345' WHERE VOLCANOIDENTIFIER = 'MTA';
